apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-app-2
  name: flask-app-2
spec:
  containers:
  - image: fnabiyev/flask-app:prac-v1
    name: flask-app
    env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: database
          key: DB_URI     
