apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: fazliddin
    project: practice
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
